### ISSUE TITLE
Readme documentation should include instructions for running virtual environment on Windows / Mac / Linux

### ISSUE THREAD

**Issue by indevelopment-tn** [inDevelopme/simwire-plugin#65]
**Is your feature request related to a problem? Please describe.**
Currently there is not any documentation on how to create a virtual environment for less experienced developers. This should be included in the README.md. Junior developers are dependent on outside sources like chatgpt for assistance for something that should be included within our readme. 

**Describe the solution you'd like**
As a developer the documentation should contain how to create a virtual environment on windows, mac, linux so that outside resources are not required for this knowledge. 

**Describe alternatives you've considered**
Is to reference users to chatgpt which can provide this information.

**Additional context**
N/A

**Comment by justaskdavidb** [comment]
This has been completed as PR https://github.com/inDevelopme/simwire-plugin/pull/71
