### ISSUE TITLE
README needs to include windows alternative for unpinning requirements.txt file dependencies

### ISSUE THREAD

**Issue by indevelopment-tn** [inDevelopme/simwire-plugin#66]
**Is your feature request related to a problem? Please describe.**
Currently the readme file does not include documentation on how to unpin dependencies after generating the requirements.txt file.

**Describe the solution you'd like**
Solution would be determine a method for performing the same actions on windows as this command does:
 `pip freeze | sed 's/==/>=/g' > requirements.txt`

**Describe alternatives you've considered**
Alternative would be to tell users to simply replace "==" with ">=" using an IDE

**Additional context**
N/A

**Comment by justaskdavidb** [comment]
This is not relevant since a simple search via an IDE would address this issue.
